# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=45, null=True)),
            ],
        ),
    ]
