# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-13 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDetail',
            fields=[
                ('detailid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('creattime', models.CharField(max_length=45)),
                ('creator', models.CharField(max_length=45)),
                ('type', models.IntegerField()),
                ('father', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='no title', max_length=45),
            preserve_default=False,
        ),
    ]
