# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-13 06:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0004_remove_course_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetail',
            new_name='Section',
        ),
    ]
