# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-13 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0005_auto_20170313_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='detailid',
            new_name='sectionid',
        ),
    ]
