# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-16 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0007_auto_20170313_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('homeworkid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('type', models.IntegerField()),
                ('answer', models.TextField()),
                ('option', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.DO_NOTHING, to='webapi.User')),
            ],
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.DO_NOTHING, to='webapi.User'),
        ),
        migrations.AlterField(
            model_name='section',
            name='creator',
            field=models.ForeignKey(db_column='creator', on_delete=django.db.models.deletion.DO_NOTHING, to='webapi.User'),
        ),
    ]
