# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-16 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0008_auto_20170316_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='homeworklist',
            field=models.TextField(blank=True, null=True),
        ),
    ]
