# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-16 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0009_section_homeworklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
