# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-16 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0010_auto_20170316_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='creattime',
            field=models.CharField(default='1', max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='homework',
            name='creator',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='section',
            name='creator',
            field=models.CharField(max_length=45),
        ),
    ]
