# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-17 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0011_auto_20170316_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='homeworklist',
            new_name='homeworkids',
        ),
    ]
