# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-17 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0012_auto_20170317_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='father',
            field=models.CharField(default=1, max_length=45),
            preserve_default=False,
        ),
    ]
