# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-21 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0014_auto_20170318_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendCourse',
            fields=[
                ('courseid', models.CharField(max_length=45, primary_key=True, serialize=False)),
            ],
        ),
    ]
