# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-24 02:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0017_notic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notic',
            old_name='contant',
            new_name='content',
        ),
    ]
