# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0019_course_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseid', models.CharField(max_length=45)),
                ('userid', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='collectcourse',
            unique_together=set([('courseid', 'userid')]),
        ),
    ]
