# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0020_auto_20170411_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('resourceid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45)),
                ('creattime', models.CharField(max_length=45)),
                ('fileurl', models.TextField()),
                ('creator', models.CharField(max_length=45)),
            ],
        ),
    ]
