# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0021_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
