# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-25 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0023_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': '\u8f6e\u64ad\u56fe', 'verbose_name_plural': '\u8f6e\u64ad\u56fe'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '\u8bfe\u7a0b', 'verbose_name_plural': '\u8bfe\u7a0b'},
        ),
        migrations.AlterModelOptions(
            name='notic',
            options={'verbose_name': '\u516c\u544a', 'verbose_name_plural': '\u516c\u544a'},
        ),
        migrations.AlterModelOptions(
            name='recommendcourse',
            options={'verbose_name': '\u9996\u9875\u8bfe\u7a0b', 'verbose_name_plural': '\u9996\u9875\u8bfe\u7a0b'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': '\u7ae0\u8282', 'verbose_name_plural': '\u7ae0\u8282'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '\u7528\u6237', 'verbose_name_plural': '\u7528\u6237'},
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=45, verbose_name='\u8bfe\u7a0b\u540d'),
        ),
        migrations.AlterField(
            model_name='recommendcourse',
            name='courseid',
            field=models.CharField(max_length=45, primary_key=True, serialize=False, verbose_name='\u8bfe\u7a0bid'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='VhVVST0qUXaCQIkslbzWib8eFlo2RW', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45, unique=True, verbose_name='\u7528\u6237\u540d'),
        ),
    ]
