# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-29 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0028_auto_20170429_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSection',
            fields=[
                ('sectionid', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=45, verbose_name='\u540d\u79f0')),
                ('creattime', models.CharField(max_length=45)),
                ('creator', models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005')),
                ('type', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('fileurl', models.CharField(blank=True, max_length=1000, null=True)),
                ('father', models.CharField(max_length=45, verbose_name='\u6240\u5c5e\u8bfe\u7a0b')),
                ('operator', models.CharField(max_length=45, verbose_name='\u5ba1\u6838')),
            ],
            options={
                'verbose_name': '\u5f85\u5ba1\u6838\u8bfe\u7a0b',
                'verbose_name_plural': '\u5f85\u5ba1\u6838\u8bfe\u7a0b',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.CharField(max_length=45, verbose_name='\u521b\u5efa\u8005'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='\u6240\u5c5e\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='notic',
            name='creattime',
            field=models.CharField(default=1493455630284L, max_length=45),
        ),
        migrations.AlterField(
            model_name='notic',
            name='noticid',
            field=models.CharField(default='3duymtmBWFuz0sMi7t50ucPvyOdmsA', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='Vujkn2TLS3Y4dQa4L2ww0fNW53qIVT', max_length=45, primary_key=True, serialize=False),
        ),
    ]
