# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-02 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0029_auto_20170429_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=45, verbose_name='\u7528\u6237id')),
                ('courseid', models.CharField(max_length=45, verbose_name='\u8bfe\u7a0bid')),
                ('sectionid', models.CharField(blank=True, max_length=45, null=True, verbose_name='\u7ae0\u8282id')),
                ('time', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '\u7528\u6237\u8bb0\u5f55',
                'verbose_name_plural': '\u7528\u6237\u8bb0\u5f55',
            },
        ),
        migrations.AlterField(
            model_name='editsection',
            name='creattime',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='notic',
            name='creattime',
            field=models.CharField(default=1493713587237L, max_length=45),
        ),
        migrations.AlterField(
            model_name='notic',
            name='noticid',
            field=models.CharField(default='j7c9rrIHZmXxDBnRm9aSavgt1s2o0X', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='u9XlPVzWzncPyImcQauEpcEdDyb8d9', max_length=45, primary_key=True, serialize=False),
        ),
    ]
