# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-04 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0032_auto_20170503_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notic',
            name='creattime',
            field=models.BigIntegerField(default=1493866545802L),
        ),
        migrations.AlterField(
            model_name='notic',
            name='noticid',
            field=models.CharField(default='7hmUrIeMPooLftxktOTPWACEDrXWAf', max_length=45, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='userid',
            field=models.CharField(default='6tzUdBbWdskSp1O1dwSLd85BRm1Q1J', max_length=45, primary_key=True, serialize=False),
        ),
    ]
