# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-07 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhtml', '0003_auto_20170307_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
