# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhtml', '0007_user_usertype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
