# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-08 03:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhtml', '0008_auto_20170308_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
